#!/usr/bin/env python3
"""Tests for the PDF-tooling policy (Albert, 2026-09-12).

Stdlib unittest, no pytest — matching the repo's stdlib-first convention.

    python3 -m unittest tests.test_pdf_tooling -v

Three distinct invariants, deliberately separate so a failure tells you which one
broke:

  1. pypdf / PyPDF2 are STRICTLY BLOCKED. Never imported, never a requirement.
     Enforced always; this one must pass everywhere.
  2. vendor/wheels is populated and locked — the repo provisioning invariant.
  3. pdfplumber actually imports — the runtime invariant.

2 and 3 FAIL rather than skip on a container where the wheels have not been
vendored yet. That is intentional: a skip would hide exactly the condition that
let a mandated tool go uninstalled for ten days in September 2026. A red test here
means "this repo is not correctly provisioned", which is true and worth surfacing.
"""

import re
import subprocess
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WHEEL_DIR = REPO_ROOT / "vendor" / "wheels"
LOCK = REPO_ROOT / "requirements.lock.txt"

FETCH_HINT = (
    "\n\nFix: follow the one-time fetch in vendor/wheels/README.md. It needs "
    "pypi.org and files.pythonhosted.org temporarily on the environment's network "
    "egress allowlist, then commits the wheels so no session ever needs the "
    "network again."
)

# Directories that are not repo source for this purpose.
SKIP_DIRS = {".git", "vendor", "analysis", "ingest", "plans", "__pycache__", ".venv"}

# Actual USAGE of the blocked packages, not prose about the ban. The block is
# documented in requirements.txt and vendor/wheels/README.md, and those mentions
# must not trip this test — so match imports and bare requirement lines only.
BLOCKED_USE = re.compile(
    r"""(
          ^\s*import\s+(pypdf|PyPDF2)\b
        | ^\s*from\s+(pypdf|PyPDF2)\b
        | ^\s*(pypdf|PyPDF2)\s*(==|>=|<=|~=|$)
    )""",
    re.IGNORECASE | re.VERBOSE | re.MULTILINE,
)


def repo_source_files():
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(REPO_ROOT).parts):
            continue
        if path.suffix.lower() in {".py", ".txt", ".sh", ".toml", ".cfg", ".json"}:
            yield path


class TestPypdfStrictlyBlocked(unittest.TestCase):
    """Albert, 2026-09-12: pypdf is a strict block, not a preference.

    Judged unreliable for reading supplier price lists. It must not appear as an
    import or a declared requirement anywhere in repo source.

    NOTE: `pypdfium2` is a DIFFERENT project (a PDFium binding) that pdfplumber
    depends on. It is not blocked, and this test must not flag it.
    """

    def test_no_pypdf_import_or_requirement_in_repo_source(self):
        offenders = []
        for path in repo_source_files():
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for m in BLOCKED_USE.finditer(text):
                line_no = text[: m.start()].count("\n") + 1
                offenders.append(
                    f"{path.relative_to(REPO_ROOT)}:{line_no}: {m.group(0).strip()}"
                )
        self.assertEqual(
            offenders, [],
            "pypdf/PyPDF2 are strictly blocked (Albert, 2026-09-12) but are "
            "imported or declared here:\n  " + "\n  ".join(offenders),
        )

    def test_pypdfium2_is_not_caught_by_the_block(self):
        """Guard against the block being over-broad and banning pdfplumber's dep."""
        self.assertIsNone(BLOCKED_USE.search("import pypdfium2"))
        self.assertIsNone(BLOCKED_USE.search("pypdfium2==4.30.0"))
        # ...while the real thing is still caught:
        self.assertIsNotNone(BLOCKED_USE.search("import pypdf"))
        self.assertIsNotNone(BLOCKED_USE.search("from PyPDF2 import PdfReader"))
        self.assertIsNotNone(BLOCKED_USE.search("pypdf==5.1.0"))


class TestVendoredWheelsPresent(unittest.TestCase):
    """Repo provisioning: the wheels and their lock are committed."""

    def test_wheel_directory_is_populated(self):
        wheels = list(WHEEL_DIR.glob("*.whl")) if WHEEL_DIR.exists() else []
        self.assertTrue(
            wheels,
            f"No .whl files in vendor/wheels/. Dependencies are vendored so an "
            f"ephemeral container never needs pypi at run time." + FETCH_HINT,
        )

    def test_lock_file_exists_and_is_hash_pinned(self):
        self.assertTrue(
            LOCK.exists(),
            f"{LOCK.name} is missing. It is generated by "
            f"scripts/write_requirements_lock.py from what pip actually "
            f"resolved — never hand-written." + FETCH_HINT,
        )
        text = LOCK.read_text(encoding="utf-8")
        self.assertIn("--hash=sha256:", text,
                      f"{LOCK.name} carries no hashes; regenerate it.")
        self.assertRegex(text, r"(?m)^pdfplumber==",
                         f"{LOCK.name} does not pin pdfplumber itself.")


class TestPdfplumberAvailable(unittest.TestCase):
    """Runtime: the only sanctioned PDF reader actually imports."""

    def test_pdfplumber_imports(self):
        proc = subprocess.run(
            [sys.executable, "-c",
             "import pdfplumber; print(pdfplumber.__version__)"],
            capture_output=True, text=True,
        )
        self.assertEqual(
            proc.returncode, 0,
            "pdfplumber does not import, so /process-price-list cannot read a "
            "price list and is required to flag and stop (step 2.0) rather than "
            "substitute another method.\n"
            f"stderr: {proc.stderr.strip()}" + FETCH_HINT,
        )


def _load_extract_module():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "pricelist_extract", REPO_ROOT / "scripts" / "pricelist_extract.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class TestCrossCheckCatchesDisagreement(unittest.TestCase):
    """The two-engine cross-check must FAIL when the engines disagree.

    A check that has only ever been observed to pass is not a check. These cases
    exercise the halting condition directly, because the real-PDF path cannot
    produce a disagreement on demand.
    """

    def setUp(self):
        self.m = _load_extract_module()

    def test_value_pdfplumber_invented_is_caught(self):
        """The failure that matters: a price PDFium cannot see anywhere."""
        agreed, plumber_only, _ = self.m.compare_values(
            ["$1.45", "$1.68", "$9.99"],   # 9.99 is the misparse
            ["$1.45", "$1.68"],
        )
        self.assertEqual(plumber_only, ["9.99"])
        self.assertEqual(agreed, ["1.45", "1.68"])

    def test_pdfium_seeing_extra_values_is_not_a_failure(self):
        """PDFium reads page prose too, so it legitimately sees more."""
        agreed, plumber_only, fium_only = self.m.compare_values(
            ["$1.45"],
            ["$1.45", "$13", "$416"],      # phone numbers, footer text, etc.
        )
        self.assertEqual(plumber_only, [], "extra PDFium values must not halt")
        self.assertEqual(fium_only, ["13", "416"])

    def test_formatting_differences_are_not_disagreement(self):
        """'$ 1,234.50' and '$1234.50' are the same value."""
        _, plumber_only, _ = self.m.compare_values(
            ["$ 1,234.50"], ["$1234.50"])
        self.assertEqual(plumber_only, [])

    def test_norm_strips_currency_formatting(self):
        self.assertEqual(self.m.norm("$ 1,234.50"), "1234.50")
        self.assertEqual(self.m.norm("$13"), "13")


class TestCatchAllTableDetection(unittest.TestCase):
    """pdfplumber emits a whole-page blob table that must be discarded.

    Column count does not distinguish it — the HOMESPRO catch-all had 4 columns,
    exactly like the real price tables. Neither does cell length on its own: see
    TestRealTableWithProseCellSurvives for the Weiss run that cost.
    """

    def setUp(self):
        self.m = _load_extract_module()

    def test_whole_page_blob_is_dropped(self):
        blob = [["TORONTO, ON " + "x" * 900, "", "", ""], ["", "", "", ""]]
        self.assertTrue(self.m.is_catch_all(blob))

    def test_real_price_table_is_kept(self):
        real = [
            [None, "", "PER SQ. FT.", "T-MOULDING"],
            ["Milan\n(5.5mm, 12 mil, 1mm IXPE, 23.90 sq ft/ box)", "",
             "$1.45", "$19.50"],
            ["Vancouver\n(8mm, 22mil, 1.5mm IXPE, 17.92 sq ft/ box) LONG PLA",
             "NK", "$1.98", "$19.50"],
        ]
        self.assertFalse(self.m.is_catch_all(real),
                         "a real table's longest cell is ~60 chars and must survive")

    def test_handles_none_cells(self):
        self.assertFalse(self.m.is_catch_all([[None, None], [None, "$1.00"]]))

    def test_empty_table_is_not_a_catch_all(self):
        self.assertFalse(self.m.is_catch_all([[None, ""], ["", None]]))


class TestRealTableWithProseCellSurvives(unittest.TestCase):
    """The Weiss regression, 2026-09-15 (Albert).

    Weiss's genuine 5-column grid encloses the page banner and the "Please Read:"
    footer inside its outermost ruling box, so one cell legitimately runs 478-832
    characters. The length-only test discarded all three pages, and the run
    reported "0 structured tables" on a sheet pdfplumber had parsed correctly —
    then halted rather than invent prices, which was right, but the halt was
    caused by this detector rather than by the document.

    A long cell now has to stand essentially ALONE before it is treated as a blob.
    The fixtures here are deliberately smaller than the real Weiss pages: an
    earlier version of the fix measured what share of the table's text the long
    cell held, which passed on the real 39-cell pages and failed on these, because
    a share is relative to table size. The count of cells beside it is not.
    """

    def setUp(self):
        self.m = _load_extract_module()

    def _weiss_shaped(self, prose_chars):
        """A real grid whose last row is one long prose cell."""
        return [
            ["Spec", "Color", "Price / SF", "SF / box", "LB / Box"],
            ['6-1/2"x3/4" T&G\n1.2mm Veneer, Wirebrush\nCharacter',
             "Bistro\nOatmeal\nTerracotta\nWarwick", "$2.99", "26.49", "62"],
            ['6-1/2"x3/4" T&G\nWirebrush\n1.2mm OAK Veneer',
             "Fortino\nRaw\nSaffron\nSandy Brown", "$3.09", "", ""],
            ['7-1/2"x3/4"xRL\nWirebrush\n2mm OAK Veneer',
             "Pewter\nCoconut\nPenny", "$3.89", "23.7", "57"],
            ["Please Read: " + "y" * prose_chars, "", "", "", ""],
        ]

    def test_grid_with_long_footer_prose_is_kept(self):
        for prose_chars in (478, 832):
            with self.subTest(prose_chars=prose_chars):
                table = self._weiss_shaped(prose_chars)
                longest = max(len(c) for row in table for c in row if c)
                self.assertGreater(
                    longest, self.m.CATCH_ALL_CELL_CHARS,
                    "fixture must exceed the length floor or it proves nothing")
                self.assertFalse(
                    self.m.is_catch_all(table),
                    "a real grid must survive one long prose cell — this is the "
                    "Weiss 2026-09-15 failure")

    def test_prices_survive_into_the_cross_check(self):
        """The point of keeping the table: its values reach the value set."""
        table = self._weiss_shaped(478)
        money = [m for row in table for c in row if c
                 for m in self.m.MONEY.findall(c)]
        self.assertEqual({self.m.norm(v) for v in money},
                         {"2.99", "3.09", "3.89"})

    def test_a_dominating_cell_is_still_a_blob(self):
        """The fix must not make the detector toothless."""
        table = [["everything " + "z" * 2000, "", "", "", ""],
                 ["", "", "$2.99", "", ""]]
        self.assertTrue(self.m.is_catch_all(table))


class TestLetterSpacedMoneyIsRead(unittest.TestCase):
    """The FAW PL-317 regression, 2026-09-20 (Albert).

    One row of FAW's July list is rendered with a space between every glyph —
    `Colors: Tobermory 7 . 2 " w i d e $ 1 . 9 9` — and the original MONEY
    pattern allowed a single space after the `$` and none after that. It
    therefore matched `$ 1` and stopped, inventing a phantom value of 1 and
    losing the real 1.99. PDFium reads the same run as `$1.99`, so the
    2026-09-12 cross-check caught it and the run halted, which is the system
    working. But the halt is also the proof that the tight pattern could
    truncate a price, and before that check existed a truncated `$1` could have
    been taken as a cost.

    The fix adds a letter-spaced alternative, tried FIRST. It requires at least
    one spaced glyph beyond the opening digit, so an ordinary `$ 2.19` does not
    match it and falls through to the tight form unchanged. That constraint is
    what these tests mostly exercise: the danger in loosening a money pattern is
    not failing to match, it is matching too much and welding two numbers into
    one.
    """

    def setUp(self):
        self.m = _load_extract_module()

    def _vals(self, text):
        return [self.m.norm(v) for v in self.m.MONEY.findall(text)]

    def test_the_actual_pl317_cell(self):
        """Verbatim from the PDF, via pdfplumber."""
        cell = 'Colors: Tobermory 7 . 2 " w i d e $ 1 . 9 9 $ 2.19 15.00 60'
        self.assertEqual(self._vals(cell), ["1.99", "2.19"])

    def test_the_same_row_unspaced_reads_identically(self):
        """The next line prices the same product normally — the two must agree."""
        self.assertEqual(self._vals('7.2" wide $1.99 $2.19 17.91 55'),
                         ["1.99", "2.19"])

    def test_a_bare_dollar_one_is_never_produced(self):
        """The exact phantom that halted the run."""
        self.assertNotIn("1", self._vals('$ 1 . 9 9'))

    def test_adjacent_numbers_are_not_welded_together(self):
        """The over-match this fix must not introduce.

        `$13 15.00` is a price followed by a separate figure. A pattern that
        allowed interior spaces freely would read it as 1315.00 — a silently
        wrong cost, which is the failure class the cross-check exists for.
        """
        for text in ("$13 15.00", "$ 13 15.00"):
            with self.subTest(text=text):
                self.assertEqual(self._vals(text), ["13"])

    def test_single_space_after_dollar_still_keeps_its_decimals(self):
        """`$ 2.19` is not letter-spaced and must survive whole."""
        self.assertEqual(self._vals("$ 2.19"), ["2.19"])

    def test_ordinary_formats_are_unchanged(self):
        self.assertEqual(self._vals("$1.45"), ["1.45"])
        self.assertEqual(self._vals("$ 1,234.50"), ["1234.50"])
        self.assertEqual(self._vals("$2.99 $3.09 $3.89"), ["2.99", "3.09", "3.89"])
        self.assertEqual(self._vals("no money here 15.00 60"), [])


if __name__ == "__main__":
    unittest.main(verbosity=2)
