#!/usr/bin/env python3
"""Tests for the PDF-tooling policy (Albert, 2026-09-12).

Stdlib unittest, no pytest — matching the repo's stdlib-first convention.

    python3 -m unittest tests.test_pdf_tooling -v

Three distinct invariants, deliberately separate so a failure tells you which one
broke:

  1. pypdf / PyPDF2 are STRICTLY BLOCKED. Never imported, never a requirement.
     Enforced always; this one must pass everywhere.
  2. vendor/wheels is populated and locked — the repo provisioning invariant.
  3. pdfplumber actually imports — the runtime invariant.

2 and 3 FAIL rather than skip on a container where the wheels have not been
vendored yet. That is intentional: a skip would hide exactly the condition that
let a mandated tool go uninstalled for ten days in September 2026. A red test here
means "this repo is not correctly provisioned", which is true and worth surfacing.
"""

import re
import subprocess
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WHEEL_DIR = REPO_ROOT / "vendor" / "wheels"
LOCK = REPO_ROOT / "requirements.lock.txt"

FETCH_HINT = (
    "\n\nFix: follow the one-time fetch in vendor/wheels/README.md. It needs "
    "pypi.org and files.pythonhosted.org temporarily on the environment's network "
    "egress allowlist, then commits the wheels so no session ever needs the "
    "network again."
)

# Directories that are not repo source for this purpose.
SKIP_DIRS = {".git", "vendor", "analysis", "ingest", "plans", "__pycache__", ".venv"}

# Actual USAGE of the blocked packages, not prose about the ban. The block is
# documented in requirements.txt and vendor/wheels/README.md, and those mentions
# must not trip this test — so match imports and bare requirement lines only.
BLOCKED_USE = re.compile(
    r"""(
          ^\s*import\s+(pypdf|PyPDF2)\b
        | ^\s*from\s+(pypdf|PyPDF2)\b
        | ^\s*(pypdf|PyPDF2)\s*(==|>=|<=|~=|$)
    )""",
    re.IGNORECASE | re.VERBOSE | re.MULTILINE,
)


def repo_source_files():
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(REPO_ROOT).parts):
            continue
        if path.suffix.lower() in {".py", ".txt", ".sh", ".toml", ".cfg", ".json"}:
            yield path


class TestPypdfStrictlyBlocked(unittest.TestCase):
    """Albert, 2026-09-12: pypdf is a strict block, not a preference.

    Judged unreliable for reading supplier price lists. It must not appear as an
    import or a declared requirement anywhere in repo source.

    NOTE: `pypdfium2` is a DIFFERENT project (a PDFium binding) that pdfplumber
    depends on. It is not blocked, and this test must not flag it.
    """

    def test_no_pypdf_import_or_requirement_in_repo_source(self):
        offenders = []
        for path in repo_source_files():
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for m in BLOCKED_USE.finditer(text):
                line_no = text[: m.start()].count("\n") + 1
                offenders.append(
                    f"{path.relative_to(REPO_ROOT)}:{line_no}: {m.group(0).strip()}"
                )
        self.assertEqual(
            offenders, [],
            "pypdf/PyPDF2 are strictly blocked (Albert, 2026-09-12) but are "
            "imported or declared here:\n  " + "\n  ".join(offenders),
        )

    def test_pypdfium2_is_not_caught_by_the_block(self):
        """Guard against the block being over-broad and banning pdfplumber's dep."""
        self.assertIsNone(BLOCKED_USE.search("import pypdfium2"))
        self.assertIsNone(BLOCKED_USE.search("pypdfium2==4.30.0"))
        # ...while the real thing is still caught:
        self.assertIsNotNone(BLOCKED_USE.search("import pypdf"))
        self.assertIsNotNone(BLOCKED_USE.search("from PyPDF2 import PdfReader"))
        self.assertIsNotNone(BLOCKED_USE.search("pypdf==5.1.0"))


class TestVendoredWheelsPresent(unittest.TestCase):
    """Repo provisioning: the wheels and their lock are committed."""

    def test_wheel_directory_is_populated(self):
        wheels = list(WHEEL_DIR.glob("*.whl")) if WHEEL_DIR.exists() else []
        self.assertTrue(
            wheels,
            f"No .whl files in vendor/wheels/. Dependencies are vendored so an "
            f"ephemeral container never needs pypi at run time." + FETCH_HINT,
        )

    def test_lock_file_exists_and_is_hash_pinned(self):
        self.assertTrue(
            LOCK.exists(),
            f"{LOCK.name} is missing. It is generated by "
            f"scripts/write_requirements_lock.py from what pip actually "
            f"resolved — never hand-written." + FETCH_HINT,
        )
        text = LOCK.read_text(encoding="utf-8")
        self.assertIn("--hash=sha256:", text,
                      f"{LOCK.name} carries no hashes; regenerate it.")
        self.assertRegex(text, r"(?m)^pdfplumber==",
                         f"{LOCK.name} does not pin pdfplumber itself.")


class TestPdfplumberAvailable(unittest.TestCase):
    """Runtime: the only sanctioned PDF reader actually imports."""

    def test_pdfplumber_imports(self):
        proc = subprocess.run(
            [sys.executable, "-c",
             "import pdfplumber; print(pdfplumber.__version__)"],
            capture_output=True, text=True,
        )
        self.assertEqual(
            proc.returncode, 0,
            "pdfplumber does not import, so /process-price-list cannot read a "
            "price list and is required to flag and stop (step 2.0) rather than "
            "substitute another method.\n"
            f"stderr: {proc.stderr.strip()}" + FETCH_HINT,
        )


def _load_extract_module():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "pricelist_extract", REPO_ROOT / "scripts" / "pricelist_extract.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class TestCrossCheckCatchesDisagreement(unittest.TestCase):
    """The two-engine cross-check must FAIL when the engines disagree.

    A check that has only ever been observed to pass is not a check. These cases
    exercise the halting condition directly, because the real-PDF path cannot
    produce a disagreement on demand.
    """

    def setUp(self):
        self.m = _load_extract_module()

    def test_value_pdfplumber_invented_is_caught(self):
        """The failure that matters: a price PDFium cannot see anywhere."""
        agreed, plumber_only, _ = self.m.compare_values(
            ["$1.45", "$1.68", "$9.99"],   # 9.99 is the misparse
            ["$1.45", "$1.68"],
        )
        self.assertEqual(plumber_only, ["9.99"])
        self.assertEqual(agreed, ["1.45", "1.68"])

    def test_pdfium_seeing_extra_values_is_not_a_failure(self):
        """PDFium reads page prose too, so it legitimately sees more."""
        agreed, plumber_only, fium_only = self.m.compare_values(
            ["$1.45"],
            ["$1.45", "$13", "$416"],      # phone numbers, footer text, etc.
        )
        self.assertEqual(plumber_only, [], "extra PDFium values must not halt")
        self.assertEqual(fium_only, ["13", "416"])

    def test_formatting_differences_are_not_disagreement(self):
        """'$ 1,234.50' and '$1234.50' are the same value."""
        _, plumber_only, _ = self.m.compare_values(
            ["$ 1,234.50"], ["$1234.50"])
        self.assertEqual(plumber_only, [])

    def test_norm_strips_currency_formatting(self):
        self.assertEqual(self.m.norm("$ 1,234.50"), "1234.50")
        self.assertEqual(self.m.norm("$13"), "13")


class TestCatchAllTableDetection(unittest.TestCase):
    """pdfplumber emits a whole-page blob table that must be discarded.

    Column count does not distinguish it — the HOMESPRO catch-all had 4 columns,
    exactly like the real price tables. Cell length does.
    """

    def setUp(self):
        self.m = _load_extract_module()

    def test_whole_page_blob_is_dropped(self):
        blob = [["TORONTO, ON " + "x" * 900, "", "", ""], ["", "", "", ""]]
        self.assertTrue(self.m.is_catch_all(blob))

    def test_real_price_table_is_kept(self):
        real = [
            [None, "", "PER SQ. FT.", "T-MOULDING"],
            ["Milan\n(5.5mm, 12 mil, 1mm IXPE, 23.90 sq ft/ box)", "",
             "$1.45", "$19.50"],
            ["Vancouver\n(8mm, 22mil, 1.5mm IXPE, 17.92 sq ft/ box) LONG PLA",
             "NK", "$1.98", "$19.50"],
        ]
        self.assertFalse(self.m.is_catch_all(real),
                         "a real table's longest cell is ~60 chars and must survive")

    def test_handles_none_cells(self):
        self.assertFalse(self.m.is_catch_all([[None, None], [None, "$1.00"]]))


if __name__ == "__main__":
    unittest.main(verbosity=2)
