#!/usr/bin/env python3
"""Plan the OneDrive -> Google Drive content migration. Moves nothing itself.

Takes a listing of the OneDrive content root and emits two artefacts:

  * migration-map.csv  — notion_id, old_name, new_name, bytes, order — reviewable
    before a single byte moves.
  * migrate.sh         — one `rclone copy` per folder, smallest first, with a
    matching `rclone check` after each.

Pure: no network, no credential, no platform call. Same split as
content_media_select.py and for the same reason — the decisions here (what gets
renamed to what, what order, what is excluded) are worth reviewing and testing on
their own, separately from the hours of byte-shuffling they describe.

    python3 scripts/content_migration_map.py --listing onedrive.json --out-dir ingest/2026-09-13/

WHY RCLONE AND NOT MAKE. Make bills data transfer monthly: Free 100MB, Core 1GB,
Pro/Teams 10GB. This job is ~200GB, and one folder (TFC-149_Tim Gilbert, 51GB) is on
its own larger than the entire monthly allowance on every tier. The Drive scenario
that creates scaffolds for NEW rows is a different job and stays as it is.

SAFETY. The generated script uses `rclone copy`, never `sync` — copy only adds, and
can never delete from either side. Nothing removes anything from OneDrive; that stays
a human decision made after verification.
"""

import argparse
import csv
import json
import re
import sys
from pathlib import Path

GB = 1024 ** 3
DEFAULT_PREFIX = "TC"
LEGACY_PREFIXES = ("TFC",)

# Not content. These sit alongside the TC-<n> folders and must never be copied as
# though they were one.
SKIP_NAMES = {"_ARCHIVE", "_TEMPLATES", "TEMPLATE"}


class MapError(RuntimeError):
    pass


def parse_name(name: str) -> tuple[int, str] | None:
    """Split 'TFC-170_QA Scratch' -> (170, 'QA Scratch'). None if not content.

    Tolerates TC-170_x, TFC-170_x and TFC170_x: all three exist right now. Keys on
    the integer, never the prefix — the prefix is exactly what is changing.
    """
    m = re.match(r"^([A-Za-z]+)[-_]?(\d+)[_\s-](.+)$", name.strip())
    if not m:
        return None
    prefix, num, rest = m.groups()
    if prefix.upper() not in {DEFAULT_PREFIX, *LEGACY_PREFIXES}:
        return None
    return int(num), rest.strip()


def new_name(notion_id: int, rest: str, prefix: str = DEFAULT_PREFIX) -> str:
    return f"{prefix}-{notion_id}_{rest}"


def build(entries: list[dict], prefix: str = DEFAULT_PREFIX) -> dict:
    rows, skipped = [], []
    seen: dict[int, str] = {}

    for e in entries:
        name = (e.get("name") or e.get("title") or "").strip()
        if not name:
            continue
        if name.upper() in SKIP_NAMES:
            skipped.append({"name": name, "reason": "not_content"})
            continue
        parsed = parse_name(name)
        if parsed is None:
            skipped.append({"name": name, "reason": "unrecognised_name"})
            continue

        notion_id, rest = parsed
        if notion_id in seen:
            # Two folders for one Notion row is a data problem, not a migration
            # problem. Copying both would silently merge them at the destination.
            raise MapError(
                f"two folders claim Notion id {notion_id}: {seen[notion_id]!r} and "
                f"{name!r}. Resolve in OneDrive before migrating — copying both would "
                "merge them into one folder at the destination.")
        seen[notion_id] = name
        rows.append({
            "notion_id": notion_id,
            "old_name": name,
            "new_name": new_name(notion_id, rest, prefix),
            "bytes": int(e.get("size") or 0),
        })

    # Smallest first: the cheap folders prove the remotes, naming and permissions
    # before a 51GB folder commits hours to a misconfiguration.
    rows.sort(key=lambda r: (r["bytes"], r["notion_id"]))
    for i, r in enumerate(rows, start=1):
        r["order"] = i

    return {"rows": rows, "skipped": skipped,
            "total_bytes": sum(r["bytes"] for r in rows)}


def write_csv(rows: list[dict], path: Path) -> None:
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["order", "notion_id", "old_name", "new_name", "bytes"])
        w.writeheader()
        for r in rows:
            w.writerow({k: r[k] for k in w.fieldnames})


def write_runner(rows: list[dict], path: Path, src_root: str, dst_root: str) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "# GENERATED by scripts/content_migration_map.py — do not hand-edit.",
        "#",
        "# rclone copy: adds only, never deletes from either side, and skips files",
        "# already present by name+size — so re-running resumes rather than restarts.",
        "# Run with DRY=1 first. Nothing is removed from OneDrive by this script, ever.",
        "set -uo pipefail",
        "",
        'DRY="${DRY:-0}"',
        'LOG="${LOG:-$HOME/titan-migration.log}"',
        '[ "$DRY" = "1" ] && EXTRA="--dry-run" || EXTRA=""',
        "",
        "FLAGS=(--progress --transfers 4 --checkers 8 --drive-chunk-size 128M",
        "       --tpslimit 10 --drive-stop-on-upload-limit",
        '       --log-file "$LOG" --log-level INFO)',
        "",
        "fail=0",
        "",
    ]
    for r in rows:
        src = f"{src_root}/{r['old_name']}"
        dst = f"{dst_root}/{r['new_name']}"
        size = f"{r['bytes'] / GB:.2f} GB" if r["bytes"] else "empty"
        lines += [
            f"# --- {r['order']}/{len(rows)}  id {r['notion_id']}  ({size}) ---",
            f'echo ">>> [{r["order"]}/{len(rows)}] {r["new_name"]}  ({size})"',
            f'rclone copy "{src}" "{dst}" "${{FLAGS[@]}}" $EXTRA || {{ echo "COPY FAILED: {r["new_name"]}"; fail=1; }}',
            # --one-way: extra files on the Drive side are fine; missing ones are not.
            f'rclone check "{src}" "{dst}" --size-only --one-way || {{ echo "CHECK FAILED: {r["new_name"]}"; fail=1; }}',
            "",
        ]
    lines += [
        'if [ "$fail" -ne 0 ]; then',
        '  echo "MIGRATION INCOMPLETE — see $LOG. Re-run this script; it resumes."',
        "  exit 1",
        "fi",
        'echo "All folders copied and verified. NOTHING has been deleted from OneDrive."',
        'echo "Next: the Notion Link to Files rewrite. Do not delete anything until that is done."',
    ]
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o755)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--listing", type=Path, help="JSON listing of the content root; default stdin")
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--prefix", default=DEFAULT_PREFIX)
    ap.add_argument("--src-root", default="onedrive:MEDIA FILES/Titan Content Files")
    ap.add_argument("--dst-root", default="gdrive:TITAN FLOORING/Titan Flooring Content")
    args = ap.parse_args()

    try:
        raw = args.listing.read_text() if args.listing else sys.stdin.read()
        data = json.loads(raw)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"bad listing: {exc}", file=sys.stderr)
        return 1

    entries = data.get("files", data) if isinstance(data, dict) else data
    try:
        plan = build(entries, args.prefix)
    except MapError as exc:
        print(f"cannot plan migration: {exc}", file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = args.out_dir / "migration-map.csv"
    sh_path = args.out_dir / "migrate.sh"
    write_csv(plan["rows"], csv_path)
    write_runner(plan["rows"], sh_path, args.src_root, args.dst_root)

    print(f"{len(plan['rows'])} folders, {plan['total_bytes'] / GB:,.1f} GB")
    print(f"  map    : {csv_path}")
    print(f"  runner : {sh_path}   (run with DRY=1 first)")
    for s in plan["skipped"]:
        print(f"  skipped: {s['name']} ({s['reason']})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
