#!/usr/bin/env python3
"""Generate requirements.lock.txt from the wheels in vendor/wheels/.

The lock is DERIVED, never hand-written. `pip download` resolves the real
transitive tree; this reads the resulting filenames and hashes them, so the lock
records what actually got fetched rather than what someone remembered the
dependency tree to be.

    python3 scripts/write_requirements_lock.py

Run it as step 2 of the fetch procedure in vendor/wheels/README.md, after
`pip download` and before committing. Writes requirements.lock.txt at the repo
root and prints a summary.

Read-only except for that one file.
"""

import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WHEEL_DIR = REPO_ROOT / "vendor" / "wheels"
LOCK = REPO_ROOT / "requirements.lock.txt"

# Wheel filename: {name}-{version}(-{build})?-{python}-{abi}-{platform}.whl
WHEEL_RE = re.compile(r"^(?P<name>[^-]+(?:-[^-]+)*?)-(?P<version>\d[^-]*)-")

# Strict block — Albert, 2026-09-12. Never vendor these.
# pypdfium2 is deliberately NOT here: different project, pdfplumber depends on it.
BLOCKED = {"pypdf", "pypdf2"}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    wheels = sorted(WHEEL_DIR.glob("*.whl"))
    if not wheels:
        print(f"No wheels in {WHEEL_DIR.relative_to(REPO_ROOT)}/ — run the "
              f"`pip download` step first (see that directory's README).",
              file=sys.stderr)
        return 1

    entries, total = [], 0
    for whl in wheels:
        m = WHEEL_RE.match(whl.name)
        if not m:
            print(f"Cannot parse wheel filename: {whl.name}", file=sys.stderr)
            return 1
        name, version = m.group("name"), m.group("version")
        normalised = name.lower().replace("_", "-")

        if normalised.replace("-", "") in BLOCKED or normalised in BLOCKED:
            print(f"BLOCKED package present in vendor/wheels: {whl.name}\n"
                  f"  pypdf/PyPDF2 are a strict block (Albert, 2026-09-12). "
                  f"Delete it and re-resolve.", file=sys.stderr)
            return 1

        entries.append((normalised, version, sha256(whl)))
        total += whl.stat().st_size

    lines = [
        "# GENERATED by scripts/write_requirements_lock.py — do not hand-edit.",
        "#",
        "# Exact versions and wheel hashes for the whole transitive tree, derived",
        "# from what `pip download` actually resolved. This is the file that gets",
        "# installed; requirements.txt is only the statement of intent.",
        "#",
        "# Installed offline from the committed wheels, no network:",
        "#   pip install --no-index --find-links vendor/wheels \\",
        "#       --only-binary=:all: --require-hashes -r requirements.lock.txt",
        "#",
        f"# {len(entries)} wheels, {total / 1_048_576:.1f} MiB total.",
        "",
    ]
    for name, version, digest in sorted(entries):
        lines.append(f"{name}=={version} \\")
        lines.append(f"    --hash=sha256:{digest}")

    LOCK.write_text("\n".join(lines) + "\n")

    print(f"Wrote {LOCK.relative_to(REPO_ROOT)}")
    print(f"  {len(entries)} wheels, {total / 1_048_576:.1f} MiB")
    for name, version, _ in sorted(entries):
        print(f"  {name}=={version}")
    if not any(n == "pdfplumber" for n, _, _ in entries):
        print("\nWARNING: pdfplumber itself is not among the wheels.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
